1.Create a vector , scaler, matrics and tensor with values of your own choice 
using tf.constant()

In [19]:
import tensorflow as tf
scalar = tf.constant(7) 
vector = tf.constant([1, 2, 3])
matrix = tf.constant([[1, 2], [3, 4]])
tensor = tf.constant([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])  

2. Find the shape and size of the tensor

In [20]:
print("Tensor Shape:", tensor.shape)
print("Tensor Size:", tf.size(tensor))

Tensor Shape: (2, 2, 2)
Tensor Size: tf.Tensor(8, shape=(), dtype=int32)


3.Create two tensors containing random values between 0 and 1 with shape (5, 300)


In [18]:
tensor_a = tf.random.uniform((5, 300), minval=0, maxval=1)
tensor_b = tf.random.uniform((5, 300), minval=0, maxval=1)


4.Multiply the two tensors using matrix multiplication (requires matching inner dimensions)

In [22]:
result_matrix_multiplication = tf.matmul(tensor_a, tensor_b, transpose_b=True)
print(result_matrix_multiplication)

tf.Tensor(
[[72.73713  66.35554  68.34963  71.61589  69.06918 ]
 [82.94262  75.2863   74.95173  84.60103  79.409874]
 [76.69995  77.66359  73.37749  79.04943  77.09665 ]
 [74.718735 69.32722  71.4311   71.489136 71.9814  ]
 [78.92394  73.060585 74.680626 78.26701  75.57319 ]], shape=(5, 5), dtype=float32)


5. Multiply the two tensors using dot product 


In [23]:
result_dot_product = tf.reduce_sum(tf.multiply(tensor_a, tensor_b), axis=1)
print("Dot Product Result:", result_dot_product)

Dot Product Result: tf.Tensor([72.73714  75.28631  73.37749  71.48914  75.573204], shape=(5,), dtype=float32)


6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3]

In [25]:
random_tensor = tf.random.uniform([224, 224, 3], minval=0, maxval=1)

7. Find the min and max values of the tensor

In [26]:
min_value = tf.reduce_min(random_tensor)
max_value = tf.reduce_max(random_tensor)
print("Min value of tensor:", min_value.numpy())
print("Max value of tensor:", max_value.numpy())

Min value of tensor: 1.04904175e-05
Max value of tensor: 0.9999981


8. Create a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3]
   

In [27]:
random_tensor_4d = tf.random.uniform([1, 224, 224, 3], minval=0, maxval=1, dtype=tf.float32)
squeezed_tensor = tf.squeeze(random_tensor_4d)
print("Shape of tensor after squeezing:", squeezed_tensor.shape)

Shape of tensor after squeezing: (224, 224, 3)


9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value

In [32]:
my_tensor = tf.constant([1, 5, 3, 9, 7, 6, 2, 8, 4, 10])
max_index = tf.argmax(my_tensor)
print("Index of max value:", max_index.numpy())

Index of max value: 9


10. One-hot encode the tensor you have created in 9

In [34]:
one_hot_encoded = tf.one_hot(max_index, depth=10)
print("One-hot encoded tensor:", one_hot_encoded.numpy())

One-hot encoded tensor: [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
